/* 
 * Meltwater Streaming API v2
 *
 * The Meltwater Streaming API provides the needed resources for Meltwater clients to create & delete REST Hooks and stream Meltwater search results to your specified destination.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@api.meltwater.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// List all hooks.     Delivers all previously generated hooks.    Requires an OAuth access token.
type HooksCollection struct {

	Hooks []Hook `json:"hooks,omitempty"`
}
