/* 
 * Meltwater Streaming API v2
 *
 * The Meltwater Streaming API provides the needed resources for Meltwater clients to create & delete REST Hooks and stream Meltwater search results to your specified destination.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: support@api.meltwater.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type ModelError struct {

	// Human-readable error message.
	Details string `json:"details,omitempty"`

	// Error title
	Title string `json:"title,omitempty"`

	// Error category
	Type_ string `json:"type,omitempty"`

	// Additional meta-information to qualify error
	Meta interface{} `json:"meta,omitempty"`
}
